title: Default Page
preset: page
options:
  changeTemplate:
    - basic
    - default
    - leistungen
    - leistungen_sub_level_one
fields:
  text:
    label: Text
    type: textarea
    size: large
 Cover:
      type: files 
      headline: Cover
      layout: cards
      template: image
      image:
          cover: true      

