title: Default Page
preset: page
options:
  changeTemplate:
    - basic
    - default
    - leistungen
    - leistungen_sub_level_one
fields:
   text:
    label: Textblock
    type: blocks
    fieldsets:
      - heading
      - text
 cover:
    type: files 
    headline: Cover
    layout: cards
    template: image
    image:
        cover: true      

